### ISSUE TITLE
dst daily gift

### ISSUE THREAD

**Issue by bakustarver** [Crestwave/dst-misc#3]
is it possible to open dst daily gifts using curl?

**Comment by Crestwave** [comment]
Good question! This should be possible, although it would require interacting with the Steamworks API to generate tickets for login, as I believe it requires a client session token.

**Comment by bakustarver** [comment]
./daily.sh: 8: ./verify.sh: not found
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100   158  100    52  100   106     70    144 --:--:-- --:--:-- --:--:--   215
ERROR

**Comment by Crestwave** [comment]
You can just comment out that if statement for now.

**Comment by Crestwave** [comment]
My daily gift has reset and I can confirm that the script works! Note that there's something up with SteamworksPy; all the tickets I generated last night were valid, while I had to try around 5 times to get a valid one right now.

```bash
$ ./daily.sh
...
{"Error":false,"GiftReceived":true,"ItemType":"BOOK_SLEEP_MAGAZINE","ItemID":[REDACTED],"Context":1}
```
![image](https://github.com/user-attachments/assets/0743fb70-eb5f-4b6d-930f-12b29297e7c3)

**Comment by bakustarver** [comment]
Thank you, everything works

I found that it is possible to download drops.json without steam using browser cookies
you need to find the session id for this

--
curl 'https://accounts.klei.com/account/transactions/drops.json' -H 'User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:131.0) Gecko/20100101 Firefox/131.0' -H 'Accept: application/json, text/plain, */*' -H 'Accept-Language: en-US,en;q=0.5' -H 'Accept-Encoding: gzip, deflate, br, zstd' -H 'Referer: https://accounts.klei.com/account/transactions' -H 'X-Requested-With: XMLHttpRequest' -H 'Connection: keep-alive' -H 'Cookie: lang=en; session=yoursessionid' -H 'Sec-Fetch-Dest: empty' -H 'Sec-Fetch-Mode: cors' -H 'Sec-Fetch-Site: same-origin' -H 'Sec-GPC: 1' -H 'TE: trailers'
get cookies from this site
https://accounts.klei.com/account/transactions



can you guide how to get curl requests in dst or other programs?

**Comment by Crestwave** [comment]
> I found that it is possible to download drops.json without steam using browser cookies
> you need to find the session id for this

Yes, of course, it's part of Klei's normal tranasctions page. I just automated it because I didn't like having to keep logging back in every now and then. :P

Similarly, you can extract the auth token from the game client instead of generating it yourself by running `print(TheFrontEnd:GetAccountManager():GetToken())` from the in-game console (note that it expires after an hour of inactivity).

> can you guide how to get curl requests in dst or other programs?

For applications like DST which respect the `https_proxy` environmental variable, you can just run a proxy server and point the env var to it to intercept the requests and analyze them.

**Comment by bakustarver** [comment]
Yes, I found the fiddler-everywhere program and was able to see the requests, also found posting DST/TICK, pity that other games don't show traffic like dst as well with https_proxy env variable

**Comment by Crestwave** [comment]
> pity that other games don't show traffic like dst as well with https_proxy env variable

You can still force them to a proxy, it's just not as convenient. It's also very likely that they might be communicating in other protocols, in which case you can use Wireshark or something similar instead.

**Comment by bakustarver** [comment]
I'm a novice at this stuff, thanks for the advice, it's really helpful.
